import { HardwareComponent, PricingTier, PortfolioProject } from "@/types";

export const hardwareComponents: HardwareComponent[] = [
  {
    id: "esp32",
    name: "ESP32-S3",
    category: "microcontroller",
    model: "ESP32-S3-WROOM-1",
    price: 8.5,
    specs: { cores: "Dual-core Xtensa", clock: "240MHz", flash: "16MB", ram: "8MB PSRAM", wifi: "802.11 b/g/n", bluetooth: "BLE 5.0" },
    icon: "Cpu",
  },
  {
    id: "rpi5",
    name: "Raspberry Pi 5",
    category: "microcontroller",
    model: "RPi 5 8GB",
    price: 80,
    specs: { cpu: "Cortex-A76 Quad", clock: "2.4GHz", ram: "8GB LPDDR4X", gpu: "VideoCore VII", pcie: "PCIe 2.0 x1", usb: "2x USB 3.0" },
    icon: "Server",
  },
  {
    id: "custom-pcb",
    name: "Custom PCB",
    category: "pcb",
    model: "4-Layer FR4",
    price: 150,
    specs: { layers: "4", material: "FR4", finish: "ENIG", thickness: "1.6mm", minTrace: "4mil", copper: "1oz" },
    icon: "CircuitBoard",
  },
  {
    id: "oled-display",
    name: "OLED Display",
    category: "display",
    model: "SSD1306 128x64",
    price: 12,
    specs: { resolution: "128x64", interface: "I2C/SPI", size: '0.96"', color: "White", voltage: "3.3-5V", driver: "SSD1306" },
    icon: "Monitor",
  },
  {
    id: "lora-module",
    name: "LoRa Module",
    category: "communication",
    model: "SX1276",
    price: 15,
    specs: { frequency: "868/915MHz", range: "15km", sensitivity: "-148dBm", power: "20dBm", interface: "SPI", spreading: "SF7-SF12" },
    icon: "Radio",
  },
  {
    id: "imu-sensor",
    name: "9-DOF IMU",
    category: "sensor",
    model: "BNO085",
    price: 22,
    specs: { axes: "9-DOF", accel: "±16g", gyro: "±2000°/s", mag: "±1300μT", interface: "I2C/SPI/UART", fusion: "Built-in" },
    icon: "Compass",
  },
  {
    id: "servo-motor",
    name: "Servo Motor",
    category: "actuator",
    model: "MG996R",
    price: 8,
    specs: { torque: "11kg·cm", voltage: "4.8-7.2V", speed: "0.17s/60°", gear: "Metal", rotation: "180°", weight: "55g" },
    icon: "Cog",
  },
  {
    id: "lipo-battery",
    name: "LiPo Battery",
    category: "power",
    model: "3.7V 3000mAh",
    price: 12,
    specs: { voltage: "3.7V", capacity: "3000mAh", discharge: "2C", connector: "JST-PH", weight: "48g", protection: "Built-in BMS" },
    icon: "Battery",
  },
];

export const portfolioProjects: PortfolioProject[] = [
  {
    id: "intelligence-platform",
    title: "Real-Time Intelligence Platform",
    subtitle: "Full-Stack Data Platform",
    description: "Multi-database intelligence system with graph-powered entity resolution, real-time alerting, and interactive network visualization across 2,300+ entities.",
    category: "platform",
    tech: ["React", "FastAPI", "PostgreSQL", "Redis", "Neo4j", "Python"],
    metrics: [
      { label: "Entities Tracked", value: "2,370" },
      { label: "Detection Rules", value: "16" },
      { label: "Real-Time Alerts", value: "486" },
      { label: "Data Sources", value: "7" },
    ],
    color: "from-blue-500 to-cyan-400",
    icon: "Network",
    features: ["Graph explorer with neighborhood traversal", "Timeline analysis with pattern detection", "Automated alert pipeline", "Interactive dossier system"],
  },
  {
    id: "algo-engine",
    title: "Algorithmic Execution Engine",
    subtitle: "Multi-Strategy Trading System",
    description: "Fleet of 10+ autonomous execution strategies with multi-broker abstraction, real-time position management, and cross-strategy risk coordination.",
    category: "automation",
    tech: ["TypeScript", "Node.js", "SQLite", "WebSocket", "REST API"],
    metrics: [
      { label: "Live Strategies", value: "10+" },
      { label: "Instruments", value: "40+" },
      { label: "Uptime", value: "99.9%" },
      { label: "Decisions/Day", value: "1,200" },
    ],
    color: "from-emerald-500 to-green-400",
    icon: "TrendingUp",
    features: ["Multi-broker abstraction layer", "Cross-strategy position safety", "Automated backtesting + optimization", "Real-time Telegram notifications"],
  },
  {
    id: "saas-platform",
    title: "White-Label SaaS Platform",
    subtitle: "Multi-Tenant Architecture",
    description: "Enterprise-grade multi-tenant platform with magic-link auth, Stripe billing, plan enforcement, and a 3-step configuration wizard.",
    category: "saas",
    tech: ["Next.js 15", "TypeScript", "Tailwind CSS", "SQLite", "Stripe"],
    metrics: [
      { label: "Source Files", value: "33" },
      { label: "API Routes", value: "18" },
      { label: "Auth Methods", value: "3" },
      { label: "Billing Tiers", value: "3" },
    ],
    color: "from-purple-500 to-violet-400",
    icon: "Layers",
    features: ["Magic link + Google OAuth + API key auth", "Stripe checkout, webhooks, portal", "Real-time dashboard with activity feeds", "Role-based access control"],
  },
  {
    id: "mobile-app",
    title: "Native Mobile Commerce App",
    subtitle: "iOS + Cross-Platform",
    description: "Production mobile app with document scanning, PDF generation, state-specific legal templates, and in-app purchases. Built, tested, and submitted to App Store.",
    category: "mobile",
    tech: ["React Native", "Expo", "Supabase", "TypeScript", "EAS Build"],
    metrics: [
      { label: "Screens", value: "9" },
      { label: "Legal Templates", value: "50" },
      { label: "Code Lines", value: "4,500" },
      { label: "Build Status", value: "Shipped" },
    ],
    color: "from-orange-500 to-amber-400",
    icon: "Smartphone",
    features: ["Camera-based document scanning", "Dynamic PDF generation", "Real-time pairing codes", "In-app purchase integration"],
  },
  {
    id: "content-pipeline",
    title: "AI Content Automation Pipeline",
    subtitle: "Autonomous Processing Engine",
    description: "Just-in-time content pipeline with AI-powered quality review, multi-stage processing, and automated publishing with intelligent scheduling.",
    category: "automation",
    tech: ["TypeScript", "Node.js", "FFmpeg", "PM2", "YouTube API"],
    metrics: [
      { label: "Processing Stages", value: "6" },
      { label: "Quality Gate", value: "AI" },
      { label: "Schedule", value: "24/7" },
      { label: "Auto-Cleanup", value: "Yes" },
    ],
    color: "from-red-500 to-pink-400",
    icon: "Zap",
    features: ["Source ranking algorithm", "AI quality reviewer (reject < 5/10)", "Automated rendering pipeline", "Zero-storage architecture"],
  },
  {
    id: "card-shop",
    title: "Card Shop Inventory Platform",
    subtitle: "Business Website + Admin System",
    description: "Custom storefront and inventory management system for a trading card retailer. AI-powered card scanner, live market pricing from TCGPlayer and eBay, and PSA graded card support.",
    category: "website",
    tech: ["Next.js 15", "TypeScript", "Tailwind CSS", "Turso", "Claude AI"],
    metrics: [
      { label: "Card Scanner", value: "AI" },
      { label: "Price Sources", value: "2" },
      { label: "Admin Tools", value: "Full" },
      { label: "Mobile", value: "100%" },
    ],
    color: "from-amber-500 to-orange-400",
    icon: "ShoppingBag",
    features: ["AI photo scanner identifies cards instantly", "Live TCGPlayer + eBay sold pricing", "PSA graded card support with cert verification", "Admin inventory management with CSV export"],
  },
  {
    id: "api-marketplace",
    title: "Developer API Marketplace",
    subtitle: "Monetized Endpoint Platform",
    description: "9-endpoint API suite with tiered billing, API key management, rate limiting, interactive playground, and AI-powered processing.",
    category: "api",
    tech: ["Next.js 15", "TypeScript", "Stripe", "Node.js", "SQLite"],
    metrics: [
      { label: "Endpoints", value: "9" },
      { label: "Pricing Tiers", value: "4" },
      { label: "Source Files", value: "22" },
      { label: "Rate Limited", value: "Yes" },
    ],
    color: "from-cyan-500 to-blue-400",
    icon: "Code",
    features: ["Interactive API playground", "Tiered billing ($0 to $99/mo)", "AI-powered text & document processing", "Auto-generated API key management"],
  },
];

export const pricingTiers: PricingTier[] = [
  {
    id: "prototype",
    name: "Prototype",
    price: 499,
    interval: "one-time",
    description: "Perfect for proof-of-concept builds and rapid prototyping.",
    features: [
      "Single hardware prototype",
      "Basic firmware development",
      "Schematic & PCB layout",
      "3D-printed enclosure",
      "2 revision cycles",
      "Source code delivery",
      "30-day email support",
    ],
    cta: "Start Prototyping",
  },
  {
    id: "product",
    name: "Product Build",
    price: 2499,
    interval: "one-time",
    description: "End-to-end product development with production-ready deliverables.",
    features: [
      "Complete hardware design",
      "Production firmware",
      "Custom PCB (4-layer)",
      "Injection-molded enclosure",
      "Mobile/web companion app",
      "OTA update system",
      "FCC/CE pre-compliance",
      "90-day priority support",
    ],
    highlighted: true,
    cta: "Build My Product",
  },
  {
    id: "saas-platform",
    name: "IoT Platform",
    price: 199,
    interval: "monthly",
    description: "Managed cloud platform for your connected hardware fleet.",
    features: [
      "Device management dashboard",
      "Real-time telemetry & alerts",
      "OTA firmware deployment",
      "REST & MQTT APIs",
      "Up to 1,000 devices",
      "99.9% uptime SLA",
      "Dedicated account manager",
      "Custom integrations",
    ],
    cta: "Subscribe Now",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 0,
    interval: "monthly",
    description: "Custom solutions for large-scale hardware deployments.",
    features: [
      "Unlimited devices",
      "White-label platform",
      "On-premise deployment",
      "Hardware co-design",
      "Dedicated engineering team",
      "24/7 phone support",
      "Custom SLA",
      "Annual hardware reviews",
    ],
    cta: "Contact Sales",
  },
];


export const services = [
  {
    title: "Hardware Design",
    description: "From napkin sketch to production-ready PCBs. Custom schematics, component selection, and DFM optimization.",
    icon: "CircuitBoard",
    features: ["Schematic capture", "PCB layout (up to 8 layers)", "BOM optimization", "DFM/DFA review"],
  },
  {
    title: "Firmware Engineering",
    description: "Bare-metal to RTOS. We write firmware that ships — reliable, efficient, and OTA-updatable.",
    icon: "Code",
    features: ["ESP-IDF / Zephyr / Arduino", "BLE/WiFi/LoRa stacks", "OTA update systems", "Power optimization"],
  },
  {
    title: "Software Integration",
    description: "Cloud dashboards, mobile apps, and APIs that talk to your hardware seamlessly.",
    icon: "Globe",
    features: ["React/Next.js dashboards", "React Native mobile apps", "REST & MQTT APIs", "Real-time telemetry"],
  },
  {
    title: "AI + Edge Computing",
    description: "Deploy ML models on microcontrollers. Intelligent edge processing for real-time decision making.",
    icon: "Brain",
    features: ["TinyML deployment", "Edge inference", "Model optimization", "Predictive maintenance"],
  },
  {
    title: "Business Websites",
    description: "Custom websites that drive sales and showcase your business. Not templates — built from scratch with admin tools to manage your own content.",
    icon: "Store",
    features: ["Custom design & branding", "Mobile-first responsive", "Admin dashboard & CMS", "SEO & performance optimized"],
  },
];

export const techStack = [
  "Next.js", "React", "TypeScript", "Node.js", "Python", "FastAPI",
  "PostgreSQL", "Redis", "Neo4j", "SQLite", "Supabase", "Stripe",
  "React Native", "Expo", "Tailwind CSS", "Framer Motion",
  "ESP-IDF", "Zephyr RTOS", "Arduino", "KiCad",
  "TensorFlow Lite", "WebSocket", "MQTT", "Docker",
];
